global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postapp-with-prometheus-grafana'
    metrics_path: '/actuator/prometheus'  # Le chemin des métriques peut varier selon la configuration de votre application
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          app: 'postapp-with-prometheus-grafana'
