apiVersion: apps/v1
kind: Deployment
metadata:
  name: postapp-deployment
  namespace: kubernetes-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postapp
  template:
    metadata:
      labels:
        app: postapp
    spec:
      containers:
        - name: postapp
          image: trk90/postapp:lastet
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postappdb-service:5432/postapp
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          ports:
            - containerPort: 8081
          command:
            - "tail"
            - "-f"
            - "/dev/null"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: postapp-service
  namespace: kubernetes-dashboard
spec:
  selector:
    app: postapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
