apiVersion: apps/v1
kind: Deployment
metadata:
  name: postapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postapp
  template:
    metadata:
      labels:
        app: postapp
    spec:
      containers:
        - name: postapp
          image: docker.io/library/postapp:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postappdb-service:5432/postapp
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: postapp-service
spec:
  selector:
    app: postapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
