apiVersion: v1
kind: Service
metadata:
  name: postappdb-service
spec:
  selector:
    app: postappdb
  ports:
    - protocol: TCP
      port: $POSTGRESDB_LOCAL_PORT
      targetPort: $POSTGRESDB_DOCKER_PORT
